### ISSUE TITLE
How exactly to use

### ISSUE THREAD

**Issue by Vampie** [furbrain/tingbot-gui#8]
Hi,

I tried to play around with it, but I can't seem to get the package working.

How exactly do I start?
I pasted the tingbot_gui folder in a new project, but that gives errors

I pasted the files directly in the folder, but that did not help.

Thank you.

**Comment by furbrain** [comment]
Hi @Vampie, sorry to hear your having problems. 
All you should need to do is create a file called `requirements.txt`, and add the line `tingbot-gui>=0.9` to this file
The tingbot OS will then install tingbot-gui for you and you should not need to install it yourself.

Alternatively, if you are running it in a simulator, you may need to run `pip install tingbot-gui`.

If neither of these options work, copy the tingbot-gui folder from the github repo into your own project and it should just work.

I have updated the docs to reflect this advice. Please let me know if it doesn't work out, or if you have any other comments on the software

Phil
